export const RESIZE_DEBOUNCE_MS = 500;
export const MIN_FRAME_SIZE = 2;
export const WEBGL_CONTEXT_ID = 'webgl2';
export const WEBGL_CONTEXT_ATTRIBUTES: WebGLContextAttributes = { premultipliedAlpha: false };
export const ZOOM_MIN = 0.1;
export const ZOOM_MAX = 8;
export const ZOOM_DELTA_THRESHOLD = 20;
export const ZOOM_STEP_TRACKPAD = 0.032;
export const ZOOM_STEP_WHEEL = 0.0768;
